# Play level variables
- name: variables form PLAY level
  hosts: localhost
  vars:
    Course: "DevOps"
    Trainer: "Siva"
    Duration: "110HRS"
  tasks:
  - name: check variables
    ansiable.builtin.debug:
      msg: "Hi I am learning {{Coures}}, Trainer is {{Trainer}}, Duration is {{Duration}}"